import json
import shutil
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import torch

from artifacts.janus_artifact.qai import (
    QAIConfig,
    QAIResNet18,
    _checkpoint_contract,
    _contract_sha256,
    _save_qai_checkpoint,
    _sha256,
    create_synthetic_qai_fixture,
    load_qai_checkpoint,
    load_qai_records,
    predict_qai,
    train_qai,
)
from artifacts.janus_artifact.schema import ValidationError


class CheckpointIntegrityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        torch.set_num_threads(1)
        cls.fixture = tempfile.TemporaryDirectory()
        cls.root = Path(cls.fixture.name)
        manifest = create_synthetic_qai_fixture(cls.root / "data")
        cls.records = load_qai_records(manifest)
        cls.config = QAIConfig(
            selected_ranks=2, base_channels=2, batch_size=4, epochs=1, seed=19
        )
        train_qai(
            cls.records,
            cls.config,
            cls.root / "checkpoint",
            device="cpu",
            run_kind="synthetic_checkpoint_integrity_test",
        )

    @classmethod
    def tearDownClass(cls):
        cls.fixture.cleanup()

    def setUp(self):
        self.work = tempfile.TemporaryDirectory()
        self.addCleanup(self.work.cleanup)
        self.checkpoint = Path(self.work.name) / "checkpoint"
        shutil.copytree(self.root / "checkpoint", self.checkpoint)

    def metadata(self):
        return json.loads((self.checkpoint / "metadata.json").read_text())

    def envelope(self):
        # Only the checkpoint generated by this test's synthetic training is read.
        return torch.load(
            self.checkpoint / "model_state.pt", map_location="cpu", weights_only=True
        )

    def write_metadata(self, metadata):
        (self.checkpoint / "metadata.json").write_text(json.dumps(metadata) + "\n")

    def rewrite_envelope(self, envelope, metadata):
        torch.save(envelope, self.checkpoint / "model_state.pt")
        metadata["weights_sha256"] = _sha256(self.checkpoint / "model_state.pt")
        self.write_metadata(metadata)

    def rebind(self, metadata):
        # Structural contracts must be checked even when ordinary digests agree.
        envelope = self.envelope()
        envelope["contract"] = _checkpoint_contract(metadata)
        envelope["contract_sha256"] = _contract_sha256(envelope["contract"])
        metadata["contract_sha256"] = envelope["contract_sha256"]
        self.rewrite_envelope(envelope, metadata)

    def test_valid_checkpoint_uses_weights_only_and_preserves_contract(self):
        original_load = torch.load
        with patch("artifacts.janus_artifact.qai.torch.load", wraps=original_load) as safe_load:
            model, metadata, device = load_qai_checkpoint(self.checkpoint, device="cpu")
        self.assertTrue(safe_load.call_args.kwargs["weights_only"])
        self.assertEqual(str(device), "cpu")
        self.assertEqual(metadata["checkpoint_version"], "janus.qai.state-dict.v2")
        self.assertEqual(
            metadata["contract_sha256"],
            _contract_sha256(_checkpoint_contract(metadata)),
        )
        self.assertFalse(model.training)

    def test_duplicate_labels_rejected_with_recomputed_digests(self):
        metadata = self.metadata()
        metadata["labels"] = ["same", "same"]
        self.rebind(metadata)
        with self.assertRaisesRegex(ValidationError, "unique and sorted"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_reordered_labels_rejected_with_recomputed_digests(self):
        metadata = self.metadata()
        metadata["labels"].reverse()
        self.rebind(metadata)
        with self.assertRaisesRegex(ValidationError, "unique and sorted"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_metadata_only_feature_config_change_rejected(self):
        metadata = self.metadata()
        metadata["config"]["selected_ranks"] += 1
        self.write_metadata(metadata)
        with self.assertRaisesRegex(ValidationError, "metadata contract digest mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_recomputed_metadata_digest_does_not_hide_state_contract_mismatch(self):
        metadata = self.metadata()
        metadata["config"]["selected_ranks"] += 1
        metadata["contract_sha256"] = _contract_sha256(_checkpoint_contract(metadata))
        self.write_metadata(metadata)
        with self.assertRaisesRegex(ValidationError, "metadata/state contract mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_all_semantic_metadata_fields_are_bound(self):
        metadata = self.metadata()
        metadata["extra_provenance_note"] = {"source": "synthetic"}
        metadata["contract_sha256"] = _contract_sha256(_checkpoint_contract(metadata))
        self.write_metadata(metadata)
        with self.assertRaisesRegex(ValidationError, "metadata/state contract mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_architecture_config_mismatch_rejected_when_bound(self):
        metadata = self.metadata()
        metadata["architecture"] = "other"
        self.rebind(metadata)
        with self.assertRaisesRegex(ValidationError, "architecture/config contract mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_token_width_config_mismatch_rejected_when_bound(self):
        metadata = self.metadata()
        metadata["config"]["token_width"] = metadata["input_shape"][0] + 1
        self.rebind(metadata)
        with self.assertRaisesRegex(ValidationError, "token width/config contract mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_unknown_config_field_rejected_when_bound(self):
        metadata = self.metadata()
        metadata["config"]["unrecognized"] = True
        self.rebind(metadata)
        with self.assertRaisesRegex(ValidationError, "config fields"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_nonfinite_state_rejected_after_valid_file_digest(self):
        for nonfinite in (float("nan"), float("inf"), -float("inf")):
            with self.subTest(nonfinite=nonfinite):
                envelope = self.envelope()
                envelope["state_dict"]["classifier.weight"][0, 0] = nonfinite
                self.rewrite_envelope(envelope, self.metadata())
                with self.assertRaisesRegex(ValidationError, "state tensor.*non-finite"):
                    load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_state_shape_config_mismatch_rejected(self):
        envelope = self.envelope()
        envelope["state_dict"]["classifier.weight"] = envelope["state_dict"]["classifier.weight"][:-1]
        self.rewrite_envelope(envelope, self.metadata())
        with self.assertRaisesRegex(ValidationError, "state/config contract mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_state_dtype_config_mismatch_rejected(self):
        envelope = self.envelope()
        envelope["state_dict"]["classifier.weight"] = envelope["state_dict"]["classifier.weight"].to(torch.float64)
        self.rewrite_envelope(envelope, self.metadata())
        with self.assertRaisesRegex(ValidationError, "state/config contract mismatch"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_save_rejects_nonfinite_state_before_serialization(self):
        state = self.envelope()["state_dict"]
        state["classifier.bias"][0] = float("nan")
        with self.assertRaisesRegex(ValidationError, "state tensor.*non-finite"):
            _save_qai_checkpoint(
                self.checkpoint / "model_state.pt", self.metadata(), state
            )

    def test_contract_rejects_nonfinite_json_metadata(self):
        metadata = self.metadata()
        metadata["run_kind"] = float("nan")
        self.write_metadata(metadata)
        with self.assertRaisesRegex(ValidationError, "finite JSON values"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_legacy_unbound_checkpoint_version_is_rejected(self):
        metadata = self.metadata()
        metadata["checkpoint_version"] = "janus.qai.state-dict.v1"
        self.write_metadata(metadata)
        with self.assertRaisesRegex(ValidationError, "unsupported"):
            load_qai_checkpoint(self.checkpoint, device="cpu")

    def test_nonfinite_inference_logits_are_rejected(self):
        def nonfinite_forward(model, features):
            return torch.full((features.shape[0], 2), float("nan"), device=features.device)
        with patch.object(QAIResNet18, "forward", nonfinite_forward):
            with self.assertRaisesRegex(ValidationError, "inference logits.*non-finite"):
                predict_qai(self.records, self.checkpoint, split="test", device="cpu")

    def test_nonfinite_inference_probabilities_are_rejected(self):
        def nonfinite_softmax(logits, dim):
            return torch.full_like(logits, float("inf"))
        with patch("artifacts.janus_artifact.qai.torch.softmax", nonfinite_softmax):
            with self.assertRaisesRegex(ValidationError, "inference probabilities.*non-finite"):
                predict_qai(self.records, self.checkpoint, split="test", device="cpu")


if __name__ == "__main__":
    unittest.main()
